=== SSWConsulting/SSW.Website-v1-archive/SSW.Website.WebUI/Standards/DeveloperXSL/rptCustomerOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:choice maxOccurs="unbounded">
<xsd:element ref="qryCustomerOrder"/>
</xsd:choice>
</xsd:complexType>
</xsd:element>
<xsd:element name="qryCustomerOrder">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CustomerID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CompanyName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="40"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="OrderID" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:integer"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Subtotal" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== SSWConsulting/SSW.Website-v1-archive/SSW.Website.WebUI/Standards/DeveloperXSL/rptCustomerOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="rptCustomerOrder.xsd">
<qryCustomerOrder>
<CustomerID>VINET</CustomerID>
<CompanyName>Vins et alcools Chevalier</CompanyName>
<OrderID>10248</OrderID>
<Subtotal>440</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>TOMSP</CustomerID>
<CompanyName>Toms Spezialitäten</CompanyName>
<OrderID>10249</OrderID>
<Subtotal>1863.4</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>HANAR</CustomerID>
<CompanyName>Hanari Carnes</CompanyName>
<OrderID>10250</OrderID>
<Subtotal>1552.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>VICTE</CustomerID>
<CompanyName>Victuailles en stock</CompanyName>
<OrderID>10251</OrderID>
<Subtotal>654.06</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>SUPRD</CustomerID>
<CompanyName>Suprêmes délices</CompanyName>
<OrderID>10252</OrderID>
<Subtotal>3597.9</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>HANAR</CustomerID>
<CompanyName>Hanari Carnes</CompanyName>
<OrderID>10253</OrderID>
<Subtotal>1444.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>CHOPS</CustomerID>
<CompanyName>Chop-suey Chinese</CompanyName>
<OrderID>10254</OrderID>
<Subtotal>556.62</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RICSU</CustomerID>
<CompanyName>Richter Supermarkt</CompanyName>
<OrderID>10255</OrderID>
<Subtotal>2490.5</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>WELLI</CustomerID>
<CompanyName>Wellington Importadora</CompanyName>
<OrderID>10256</OrderID>
<Subtotal>517.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>HILAA</CustomerID>
<CompanyName>HILARIÓN-Abastos</CompanyName>
<OrderID>10257</OrderID>
<Subtotal>1119.9</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>ERNSH</CustomerID>
<CompanyName>Ernst Handel</CompanyName>
<OrderID>10258</OrderID>
<Subtotal>1614.88</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>CENTC</CustomerID>
<CompanyName>Centro comercial Moctezuma</CompanyName>
<OrderID>10259</OrderID>
<Subtotal>100.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>OTTIK</CustomerID>
<CompanyName>Ottilies Käseladen</CompanyName>
<OrderID>10260</OrderID>
<Subtotal>1504.65</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>QUEDE</CustomerID>
<CompanyName>Que Delícia</CompanyName>
<OrderID>10261</OrderID>
<Subtotal>448</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RATTC</CustomerID>
<CompanyName>Rattlesnake Canyon Grocery</CompanyName>
<OrderID>10262</OrderID>
<Subtotal>584</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>ERNSH</CustomerID>
<CompanyName>Ernst Handel</CompanyName>
<OrderID>10263</OrderID>
<Subtotal>1873.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>FOLKO</CustomerID>
<CompanyName>Folk och fä HB</CompanyName>
<OrderID>10264</OrderID>
<Subtotal>695.62</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>BLONP</CustomerID>
<CompanyName>Blondel père et fils</CompanyName>
<OrderID>10265</OrderID>
<Subtotal>1176</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>WARTH</CustomerID>
<CompanyName>Wartian Herkku</CompanyName>
<OrderID>10266</OrderID>
<Subtotal>346.56</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>FRANK</CustomerID>
<CompanyName>Frankenversand</CompanyName>
<OrderID>10267</OrderID>
<Subtotal>3536.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>GROSR</CustomerID>
<CompanyName>GROSELLA-Restaurante</CompanyName>
<OrderID>10268</OrderID>
<Subtotal>1101.2</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>WHITC</CustomerID>
<CompanyName>White Clover Markets</CompanyName>
<OrderID>10269</OrderID>
<Subtotal>642.2</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>WARTH</CustomerID>
<CompanyName>Wartian Herkku</CompanyName>
<OrderID>10270</OrderID>
<Subtotal>1376</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>SPLIR</CustomerID>
<CompanyName><![CDATA[Split Rail Beer & Ale]]></CompanyName>
<OrderID>10271</OrderID>
<Subtotal>48</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RATTC</CustomerID>
<CompanyName>Rattlesnake Canyon Grocery</CompanyName>
<OrderID>10272</OrderID>
<Subtotal>1456</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>QUICK</CustomerID>
<CompanyName>QUICK-Stop</CompanyName>
<OrderID>10273</OrderID>
<Subtotal>2037.28</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>VINET</CustomerID>
<CompanyName>Vins et alcools Chevalier</CompanyName>
<OrderID>10274</OrderID>
<Subtotal>538.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>MAGAA</CustomerID>
<CompanyName>Magazzini Alimentari Riuniti</CompanyName>
<OrderID>10275</OrderID>
<Subtotal>291.84</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>TORTU</CustomerID>
<CompanyName>Tortuga Restaurante</CompanyName>
<OrderID>10276</OrderID>
<Subtotal>420</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>MORGK</CustomerID>
<CompanyName>Morgenstern Gesundkost</CompanyName>
<OrderID>10277</OrderID>
<Subtotal>1200.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>BERGS</CustomerID>
<CompanyName>Berglunds snabbköp</CompanyName>
<OrderID>10278</OrderID>
<Subtotal>1488.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>LEHMS</CustomerID>
<CompanyName>Lehmanns Marktstand</CompanyName>
<OrderID>10279</OrderID>
<Subtotal>351</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>BERGS</CustomerID>
<CompanyName>Berglunds snabbköp</CompanyName>
<OrderID>10280</OrderID>
<Subtotal>613.2</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>ROMEY</CustomerID>
<CompanyName>Romero y tomillo</CompanyName>
<OrderID>10281</OrderID>
<Subtotal>86.5</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>ROMEY</CustomerID>
<CompanyName>Romero y tomillo</CompanyName>
<OrderID>10282</OrderID>
<Subtotal>155.4</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>LILAS</CustomerID>
<CompanyName>LILA-Supermercado</CompanyName>
<OrderID>10283</OrderID>
<Subtotal>1414.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>LEHMS</CustomerID>
<CompanyName>Lehmanns Marktstand</CompanyName>
<OrderID>10284</OrderID>
<Subtotal>1170.37</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>QUICK</CustomerID>
<CompanyName>QUICK-Stop</CompanyName>
<OrderID>10285</OrderID>
<Subtotal>1743.36</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>QUICK</CustomerID>
<CompanyName>QUICK-Stop</CompanyName>
<OrderID>10286</OrderID>
<Subtotal>3016</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RICAR</CustomerID>
<CompanyName>Ricardo Adocicados</CompanyName>
<OrderID>10287</OrderID>
<Subtotal>819</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>REGGC</CustomerID>
<CompanyName>Reggiani Caseifici</CompanyName>
<OrderID>10288</OrderID>
<Subtotal>80.1</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>BSBEV</CustomerID>
<CompanyName><![CDATA[B's Beverages]]></CompanyName>
<OrderID>10289</OrderID>
<Subtotal>479.4</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>COMMI</CustomerID>
<CompanyName>Comércio Mineiro</CompanyName>
<OrderID>10290</OrderID>
<Subtotal>2169</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>QUEDE</CustomerID>
<CompanyName>Que Delícia</CompanyName>
<OrderID>10291</OrderID>
<Subtotal>497.52</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>TRADH</CustomerID>
<CompanyName>Tradição Hipermercados</CompanyName>
<OrderID>10292</OrderID>
<Subtotal>1296</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>TORTU</CustomerID>
<CompanyName>Tortuga Restaurante</CompanyName>
<OrderID>10293</OrderID>
<Subtotal>848.7</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RATTC</CustomerID>
<CompanyName>Rattlesnake Canyon Grocery</CompanyName>
<OrderID>10294</OrderID>
<Subtotal>1887.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>VINET</CustomerID>
<CompanyName>Vins et alcools Chevalier</CompanyName>
<OrderID>10295</OrderID>
<Subtotal>121.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>LILAS</CustomerID>
<CompanyName>LILA-Supermercado</CompanyName>
<OrderID>10296</OrderID>
<Subtotal>1050.6</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>BLONP</CustomerID>
<CompanyName>Blondel père et fils</CompanyName>
<OrderID>10297</OrderID>
<Subtotal>1420</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>HUNGO</CustomerID>
<CompanyName>Hungry Owl All-Night Grocers</CompanyName>
<OrderID>10298</OrderID>
<Subtotal>2645</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>RICAR</CustomerID>
<CompanyName>Ricardo Adocicados</CompanyName>
<OrderID>10299</OrderID>
<Subtotal>349.5</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>MAGAA</CustomerID>
<CompanyName>Magazzini Alimentari Riuniti</CompanyName>
<OrderID>10300</OrderID>
<Subtotal>608</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>WANDK</CustomerID>
<CompanyName>Die Wandernde Kuh</CompanyName>
<OrderID>10301</OrderID>
<Subtotal>755</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>SUPRD</CustomerID>
<CompanyName>Suprêmes délices</CompanyName>
<OrderID>10302</OrderID>
<Subtotal>2708.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>GODOS</CustomerID>
<CompanyName>Godos Cocina Típica</CompanyName>
<OrderID>10303</OrderID>
<Subtotal>1117.8</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>TORTU</CustomerID>
<CompanyName>Tortuga Restaurante</CompanyName>
<OrderID>10304</OrderID>
<Subtotal>954.4</Subtotal>
</qryCustomerOrder>
<qryCustomerOrder>
<CustomerID>OLDWO</CustomerID>
<CompanyName>Old World Delicatessen</CompanyName>
<OrderID>10305</OrderID>
<Subtotal>3741.3</Subtotal>
